export const RISK_SCALE = [9, 5, 3, 1, 0];

export const EVIDENCE_OPTIONS = [
  "Similar issue exists",
  "Complex conditions",
  "External dependency",
  "Result accuracy impact",
  "User misunderstanding risk",
  "Side-effect concern",
  "Environment constraint",
];

export const PRIORITY_META = {
  Critical: "bg-red-50 text-red-700 border-red-200 ring-red-500/10",
  High: "bg-orange-50 text-orange-700 border-orange-200 ring-orange-500/10",
  Moderate: "bg-amber-50 text-amber-700 border-amber-200 ring-amber-500/10",
  Low: "bg-sky-50 text-sky-700 border-sky-200 ring-sky-500/10",
  None: "bg-slate-100 text-slate-600 border-slate-200 ring-slate-500/10",
};

export const INITIAL_ITEMS = [
  {
    id: 1,
    project: "BCM",
    product: "Viewer",
    release: "1.3.0-qa.2",
    title: "Result Summary 필터 유지 로직",
    relatedArea: "Summary",
    description: "Result Summary 탭에서 필터 변경값 유지 로직 변경",
    changeType: "Modify",
    riskType: "Product",
    changeSummary: "필터 상태 유지 방식 수정",
    concernScenario: "화면 이동 후 이전 필터 상태가 비정상적으로 유지되거나 초기화되지 않을 수 있음",
    likelihood: 9,
    impact: 5,
    evidenceFlags: ["Similar issue exists", "Complex conditions", "Result accuracy impact", "Side-effect concern"],
    likelihoodReason: "화면 상태 유지와 탭 이동이 연결되어 있고 과거 유사 이슈가 존재함",
    impactReason: "사용자가 잘못된 필터 상태를 보고 결과를 오해할 수 있음",
    dependencyArea: "Viewer / Summary / Filter State",
    testConstraints: "실제 데이터 조합별 확인 필요",
    focusPoints: "탭 이동, 화면 재진입, 기본값 초기화, Reset 동작",
    regressionRequired: true,
    logCheckRequired: true,
    extraReviewRequired: false,
    status: "Reviewing",
    fromCapture: false,
    updatedAt: "2026-03-24 10:20",
  },
  {
    id: 2,
    project: "BCM",
    product: "Viewer",
    release: "1.3.0-qa.2",
    title: "CSV Export Patient ID 처리",
    relatedArea: "CSV",
    description: "Patient ID 미입력값 표시 포맷 수정",
    changeType: "Modify",
    riskType: "Product",
    changeSummary: "UNKNOWN -> Unknown 표기 변경",
    concernScenario: "표시 문자열 수정 중 다른 CSV 필드 포맷에 부작용 발생 가능",
    likelihood: 5,
    impact: 5,
    evidenceFlags: ["Similar issue exists", "User misunderstanding risk"],
    likelihoodReason: "CSV export 포맷 처리 로직이 공통 함수에 묶여 있음",
    impactReason: "사용자 문서 해석 혼선 및 CS 문의 가능",
    dependencyArea: "CSV Export / Patient Info",
    testConstraints: "다국어/빈값 케이스 확인 필요",
    focusPoints: "빈값, 공백, 영문 대소문자, 기존 CSV 헤더 영향",
    regressionRequired: true,
    logCheckRequired: false,
    extraReviewRequired: false,
    status: "Confirmed",
    fromCapture: false,
    updatedAt: "2026-03-24 09:10",
  },
  {
    id: 3,
    project: "BCM",
    product: "Viewer",
    release: "1.3.0-qa.2",
    title: "테스트 환경 준비 지연",
    relatedArea: "Environment",
    description: "검증용 환경 세팅 지연",
    changeType: "Maintenance",
    riskType: "Project",
    changeSummary: "검증 일정 내 환경 준비 미완료",
    concernScenario: "핵심 시나리오 검증 범위가 축소될 수 있음",
    likelihood: 5,
    impact: 3,
    evidenceFlags: ["Environment constraint"],
    likelihoodReason: "환경 세팅 선행 작업이 남아 있음",
    impactReason: "검증 착수 및 종료 기준 일정에 영향",
    dependencyArea: "Test Environment / Data Set",
    testConstraints: "실장비/실검체 사용 제약",
    focusPoints: "우선 검증 대상 재정의, 대체 환경 활용",
    regressionRequired: false,
    logCheckRequired: false,
    extraReviewRequired: true,
    status: "Draft",
    fromCapture: false,
    updatedAt: "2026-03-23 18:40",
  },
];

export const EMPTY_FORM = {
  id: null,
  project: "BCM",
  product: "Viewer",
  release: "1.3.0-qa.2",
  title: "",
  relatedArea: "",
  description: "",
  changeType: "Modify",
  riskType: "Product",
  changeSummary: "",
  concernScenario: "",
  likelihood: 0,
  impact: 0,
  evidenceFlags: [],
  likelihoodReason: "",
  impactReason: "",
  dependencyArea: "",
  testConstraints: "",
  focusPoints: "",
  regressionRequired: false,
  logCheckRequired: false,
  extraReviewRequired: false,
  status: "Draft",
  fromCapture: false,
};
